language: scala
scala:
- 2.13.1
- 2.12.10
jdk:
- openjdk8
- openjdk11
sudo: false
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete -print
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete -print
script: sbt ++$TRAVIS_SCALA_VERSION test
